### ISSUE TITLE
Cant get it to work.

### ISSUE THREAD

**Issue by vgogov** [lishiyo/hqtrivia#3]
I'm having an issue getting to work, or I am not understanding the instructions correctly. I've put in all my Google keys, but where I'm stuck is the IMAGE_PATH variable. I have quicktime setup where I can see the Iphone mirror. I put the quicktime in the top-left corner. If I run the main.py sricpt it throws the error:
"ImportError: No module named google.oauth2". Is there a specific thing for IMAGE_PATH or am I missing something else? Thanks!

**Comment by vgogov** [comment]
After toying around a bit i managed to figure it out. I just set IMAGE_PATH to sample.png and it all works.

**Comment by Cyberdad5828** [comment]
can you tell me which file to open in python

**Comment by dinesh010** [comment]
main.py from command line
